# Generated by Django 5.2.16 on 2026-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name_plural': 'Asset categories'},
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='file',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
