# Generated by Django 5.2.16 on 2026-07-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assetcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assetevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('relocated', 'Relocated'), ('status_changed', 'Status Changed'), ('retired', 'Retired'), ('flagged_missing', 'Flagged Missing'), ('quantity_adjusted', 'Quantity Adjusted')], max_length=30),
        ),
    ]
