# Generated by Django 5.2.16 on 2026-07-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetloan',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
